from django.urls import path

from .views import (
    admin_backups,
    admin_backups_create,
    admin_backups_download,
    admin_backups_restore,
    admin_click_signal_reset,
    admin_click_signal_snapshot_reset,
    admin_export_csv,
    admin_index_backups,
    admin_index_refresh,
    admin_index_restore,
    admin_index_status,
    admin_index_sync_status,
    admin_index_sync_django,
    admin_index_sync_reset_watermark,
    admin_assistant_status,
    admin_search_crawl,
    admin_search_export,
    admin_search_ranking_config,
    admin_search_rewrite_rules,
    admin_search_rewrite_rules_suggestions,
    admin_search_rewrite_rules_update,
    admin_search_seed,
    admin_search_status,
    admin_runtime_metrics,
    admin_overview,
    admin_routing,
    admin_routing_verify,
    analytics_popular_searches,
    assistant_chat,
    auth_login,
    health,
    location_auto,
    page_view,
    result_click,
    search,
    search_related,
    search_suggest,
    search_sources,
    search_trending,
)

urlpatterns = [
    path("auth/login", auth_login, name="auth-login"),
    path("health", health, name="health"),
    path("location/auto", location_auto, name="location-auto"),
    path("search", search, name="search"),
    path("search/suggest", search_suggest, name="search-suggest"),
    path("search/sources", search_sources, name="search-sources"),
    path("search/trending", search_trending, name="search-trending"),
    path("search/related", search_related, name="search-related"),
    path("analytics/popular-searches", analytics_popular_searches, name="analytics-popular-searches"),
    path("events/page-view", page_view, name="page-view"),
    path("events/result-click", result_click, name="result-click"),
    path("assistant/chat", assistant_chat, name="assistant-chat"),
    path("admin/overview", admin_overview, name="admin-overview"),
    path("admin/click-signal/reset", admin_click_signal_reset, name="admin-click-signal-reset"),
    path("admin/click-signal/snapshot-reset", admin_click_signal_snapshot_reset, name="admin-click-signal-snapshot-reset"),
    path("admin/assistant-status", admin_assistant_status, name="admin-assistant-status"),
    path("admin/runtime-metrics", admin_runtime_metrics, name="admin-runtime-metrics"),
    path("admin/search/status", admin_search_status, name="admin-search-status"),
    path("admin/search/ranking-config", admin_search_ranking_config, name="admin-search-ranking-config"),
    path("admin/search/rewrite-rules", admin_search_rewrite_rules, name="admin-search-rewrite-rules"),
    path("admin/search/rewrite-rules/suggestions", admin_search_rewrite_rules_suggestions, name="admin-search-rewrite-rules-suggestions"),
    path("admin/search/rewrite-rules/update", admin_search_rewrite_rules_update, name="admin-search-rewrite-rules-update"),
    path("admin/search/seed", admin_search_seed, name="admin-search-seed"),
    path("admin/search/crawl", admin_search_crawl, name="admin-search-crawl"),
    path("admin/search/export", admin_search_export, name="admin-search-export"),
    path("admin/routing", admin_routing, name="admin-routing"),
    path("admin/routing/verify", admin_routing_verify, name="admin-routing-verify"),
    path("admin/backups", admin_backups, name="admin-backups"),
    path("admin/backups/download", admin_backups_download, name="admin-backups-download"),
    path("admin/backups/create", admin_backups_create, name="admin-backups-create"),
    path("admin/backups/restore", admin_backups_restore, name="admin-backups-restore"),
    path("admin/export.csv", admin_export_csv, name="admin-export-csv"),
    path("admin/index/backups", admin_index_backups, name="admin-index-backups"),
    path("admin/index/refresh", admin_index_refresh, name="admin-index-refresh"),
    path("admin/index/restore", admin_index_restore, name="admin-index-restore"),
    path("admin/index/status", admin_index_status, name="admin-index-status"),
    path("admin/index/sync-status", admin_index_sync_status, name="admin-index-sync-status"),
    path("admin/index/sync-django", admin_index_sync_django, name="admin-index-sync-django"),
    path("admin/index/sync-reset-watermark", admin_index_sync_reset_watermark, name="admin-index-sync-reset-watermark"),
]
